const EMOT_IN_COMMENT = 'EMOT_IN_COMMENT';
const TEXT_IN_COMMENT = 'TEXT_IN_COMMENT';
const IMG_IN_COMMENT = 'IMG_IN_COMMENT';
const HTML_TAG_IN_COMMENT = 'HTML_TAG_IN_COMMENT';

export {
  EMOT_IN_COMMENT,
  TEXT_IN_COMMENT,
  IMG_IN_COMMENT,
  HTML_TAG_IN_COMMENT,
};
